version: "3"

services:
  node-app:
    container_name: express-node-app-dev
    build:
      context: .
      target: development        # ðŸ”¥ Ø£Ù‡Ù… Ø³Ø·Ø±
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules        # ðŸ”¥ ÙŠØ­Ù…ÙŠ nodemon
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start_dev"]
